"""test

Revision ID: 009be41605aa
Revises: 6f8f84c22a03
Create Date: 2023-04-21 23:55:34.433699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009be41605aa'
down_revision = '6f8f84c22a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_converter', sa.Column('rate', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_converter', 'rate')
    # ### end Alembic commands ###
