"""fix

Revision ID: 6d708f4f79b3
Revises: ac1825399906
Create Date: 2023-04-21 23:52:37.795767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d708f4f79b3'
down_revision = 'ac1825399906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
