"""fix

Revision ID: 950f9d87fc2b
Revises: 8d99d0173303
Create Date: 2023-04-21 23:49:16.595017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950f9d87fc2b'
down_revision = '8d99d0173303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
